'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {Readable}=require('node:stream');
const {createAppHandler}=require('./app-server');const {createFixture}=require('./test-support/app-fixture.cjs');
class HttpError extends Error {constructor(status,message,payload){super(message);this.status=status;this.payload=payload;}}
function harness({production=false,override}={}){
 const calls=[];const fixture=createFixture();
 const handler=createAppHandler({production,secret:'test-secret-for-isolated-app-only',HttpError,json:(res,status,body)=>{res.status=status;res.body=body;},readBody:async req=>req.body,api:async(...args)=>{calls.push(args);const result=override?.(...args);return result===undefined?fixture(...args):result;}});
 async function request(path,{method='GET',body,cookie,origin=production?'https://movly.test':'http://movly.test',headers={}}={}){
  const req=Readable.from([]);req.method=method;req.body=body;req.headers={host:'movly.test',origin,'x-movly-app':'1',...(cookie?{cookie}:{}),...headers};const res={headers:{},setHeader(k,v){this.headers[k]=v;}};
  try{await handler(req,res,new URL(`http://movly.test/api/app/${path}`));}catch(e){res.status=e.status;res.body={message:e.message};}
  return {...res,cookie:res.headers['Set-Cookie']?.split(';')[0]};
 }
 async function login(){return request('login',{method:'POST',body:{username:'test',password:'movly-test'}});}
 async function selected(){const l=await login();return request('profile',{method:'POST',cookie:l.cookie,body:{id:1}});}
 return{request,login,selected,calls};
}
test('anonymous catalog never calls API-key-readable upstream',async()=>{const h=harness(),r=await h.request('main');assert.equal(r.status,401);assert.equal(h.calls.length,0);});
test('login keeps bearer encrypted in HttpOnly cookie with production flags',async()=>{const h=harness({production:true}),r=await h.login();assert.equal(r.status,200);assert.ok(!JSON.stringify(r.body).includes('fixture-token'));assert.match(r.headers['Set-Cookie'],/^__Host-movly-app=/);assert.match(r.headers['Set-Cookie'],/HttpOnly; SameSite=Strict; Max-Age=\d+; Secure/);assert.ok(!r.cookie.includes('fixture-token'));assert.equal(h.calls[0][5]['X-Platform'],'web');assert.equal(h.calls[0][2].device_type,'web');});
test('cross-origin login and mutation rejected before upstream',async()=>{const h=harness();const r=await h.request('login',{method:'POST',origin:'https://evil.test',body:{username:'test',password:'movly-test'}});assert.equal(r.status,403);assert.equal(h.calls.length,0);});
test('tampered encrypted cookie rejected',async()=>{const h=harness(),l=await h.login();const r=await h.request('main',{cookie:l.cookie.replace(/=(.)/,(_,c)=>`=${c==='A'?'B':'A'}`)});assert.equal(r.status,401);});
test('profile selection supplies explicit identity and ignores client overrides',async()=>{const h=harness(),s=await h.selected();assert.equal(s.status,200);const r=await h.request('main?type=movie&limit=12',{cookie:s.cookie,headers:{'x-profile-id':'999','x-profile-grant':'evil'}});assert.equal(r.status,200);const c=h.calls.at(-1);assert.equal(c[0],'v1/main/?type=movie&limit=12&lang=cs');assert.equal(c[5]['X-Profile-ID'],'1');assert.equal(c[5]['X-Profile-Grant'],'grant-1');});
test('session without selected profile cannot read catalog',async()=>{const h=harness(),l=await h.login(),r=await h.request('search?q=test',{cookie:l.cookie});assert.equal(r.status,409);assert.equal(r.body.code,'app_profile_required');});
test('wrong PIN preserves login; valid PIN obtains selected grant',async()=>{const h=harness(),l=await h.login();const bad=await h.request('profile',{method:'POST',cookie:l.cookie,body:{id:2,pin:'0000'}});assert.equal(bad.status,401);assert.equal(bad.cookie,undefined);const good=await h.request('profile',{method:'POST',cookie:l.cookie,body:{id:2,pin:'1234'}});assert.equal(good.status,200);assert.equal(good.body.profile.id,2);assert.ok(!JSON.stringify(good.body).includes('grant'));});
test('session revocation blocks catalog and clears cookie',async()=>{const h=harness(),s=await h.selected();await h.request('logout',{method:'POST',cookie:s.cookie});const r=await h.request('main',{cookie:s.cookie});assert.equal(r.status,401);assert.match(r.headers['Set-Cookie'],/Max-Age=0/);});
test('closed routes reject unknown paths, filters and streams',async()=>{const h=harness(),s=await h.selected();for(const path of ['streaming/titles/1/streams','titles/1?expand=streams','main?type=movie&type=tv','main?limit=99999']){const r=await h.request(path,{cookie:s.cookie});assert.ok([400,404].includes(r.status));}assert.ok(!h.calls.some(c=>c[0].includes('streaming/')));});
test('watchlist changes use canonical upstream and strip extra fields',async()=>{const h=harness(),s=await h.selected();const created=await h.request('watchlists',{method:'POST',cookie:s.cookie,body:{name:' Nový ',is_public:true,user_id:999}});assert.equal(created.status,200);assert.deepEqual(h.calls.at(-1)[2],{name:'Nový',description:null,is_public:false});const id=created.body.id;await h.request(`watchlists/${id}/items`,{method:'POST',cookie:s.cookie,body:{title_id:1}});const items=await h.request(`watchlists/${id}`,{cookie:s.cookie});assert.equal(items.body[0].title_id,1);const dup=await h.request(`watchlists/${id}/items`,{method:'POST',cookie:s.cookie,body:{title_id:1}});assert.equal(dup.status,409);await h.request(`watchlists/${id}/items/${items.body[0].id}`,{method:'DELETE',cookie:s.cookie});assert.deepEqual((await h.request(`watchlists/${id}`,{cookie:s.cookie})).body,[]);});
test('partial upstream results remain explicitly degraded',async()=>{const payload={lists:[],total_lists:0,degraded:true,degraded_sources:['recommendations']};const h=harness({override:p=>p.startsWith('v1/main/')?{payload}:undefined}),s=await h.selected();assert.deepEqual((await h.request('main',{cookie:s.cookie})).body,payload);});
test('missing profile grant fails closed',async()=>{const h=harness({override:p=>p.endsWith('/select')?{payload:{profile_id:1,name:'Test'}}:undefined}),l=await h.login();const r=await h.request('profile',{method:'POST',cookie:l.cookie,body:{id:1}});assert.equal(r.status,502);assert.equal(r.cookie,undefined);});
test('expired grant cannot block logout or profile re-selection',async()=>{const h=harness(),s=await h.selected();await h.request('profiles',{cookie:s.cookie});const identities=h.calls.filter(c=>['v1/auth/me','v1/profiles'].includes(c[0]));assert.ok(identities.every(c=>!c[5]['X-Profile-Grant']));await h.request('logout',{method:'POST',cookie:s.cookie});assert.equal(h.calls.at(-1)[5]['X-Profile-Grant'],undefined);});
test('malformed JSON body returns 400 instead of internal error',async()=>{const h=harness();for(const body of [null,[],4])assert.equal((await h.request('login',{method:'POST',body})).status,400);});
